"""Schema definitions and version constants.

SCHEMA_VERSION is incremented for every structural change.
Migrations are applied in order; never edit applied migrations in place.
"""

from __future__ import annotations

SCHEMA_VERSION = 1

# All timestamps are stored as ISO-8601 UTC strings (TEXT) for portability.
# IDs are TEXT UUIDs generated by the application layer.

MIGRATIONS: dict[int, str] = {
    1: """
    PRAGMA foreign_keys = ON;

    CREATE TABLE IF NOT EXISTS schema_version (
        version     INTEGER PRIMARY KEY,
        applied_at  TEXT NOT NULL,
        description TEXT
    );

    CREATE TABLE IF NOT EXISTS agent_state (
        key         TEXT PRIMARY KEY,
        value_json  TEXT NOT NULL,
        updated_at  TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS strategies (
        strategy_id     TEXT PRIMARY KEY,
        name            TEXT NOT NULL,
        status          TEXT NOT NULL DEFAULT 'GENERATED',
        parent_id       TEXT,
        generation      INTEGER NOT NULL DEFAULT 0,
        created_at      TEXT NOT NULL,
        updated_at      TEXT NOT NULL,
        metadata_json   TEXT NOT NULL DEFAULT '{}',
        FOREIGN KEY (parent_id) REFERENCES strategies(strategy_id)
    );
    CREATE INDEX IF NOT EXISTS idx_strategies_status ON strategies(status);

    CREATE TABLE IF NOT EXISTS strategy_versions (
        version_id      TEXT PRIMARY KEY,
        strategy_id     TEXT NOT NULL,
        version_num     INTEGER NOT NULL,
        genome_json     TEXT NOT NULL,
        lineage_json    TEXT NOT NULL DEFAULT '{}',
        created_at      TEXT NOT NULL,
        UNIQUE(strategy_id, version_num),
        FOREIGN KEY (strategy_id) REFERENCES strategies(strategy_id)
    );
    CREATE INDEX IF NOT EXISTS idx_sv_strategy ON strategy_versions(strategy_id);

    CREATE TABLE IF NOT EXISTS observations (
        observation_id  TEXT PRIMARY KEY,
        timestamp       TEXT NOT NULL,
        symbol          TEXT,
        timeframe       TEXT,
        market_state_json TEXT NOT NULL DEFAULT '{}',
        features_json   TEXT NOT NULL DEFAULT '{}',
        regime          TEXT,
        source          TEXT,
        content_hash    TEXT,
        created_at      TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_obs_ts ON observations(timestamp);
    CREATE INDEX IF NOT EXISTS idx_obs_symbol ON observations(symbol);

    CREATE TABLE IF NOT EXISTS decisions (
        decision_id     TEXT PRIMARY KEY,
        timestamp       TEXT NOT NULL,
        symbol          TEXT,
        timeframe       TEXT,
        action          TEXT NOT NULL,
        strategy_id     TEXT,
        strategy_version INTEGER,
        policy_version  TEXT,
        volume          REAL,
        sl              REAL,
        tp              REAL,
        confidence      REAL,
        regime          TEXT,
        reasoning_json  TEXT NOT NULL DEFAULT '{}',
        observation_id  TEXT,
        created_at      TEXT NOT NULL,
        FOREIGN KEY (strategy_id) REFERENCES strategies(strategy_id),
        FOREIGN KEY (observation_id) REFERENCES observations(observation_id)
    );
    CREATE INDEX IF NOT EXISTS idx_dec_ts ON decisions(timestamp);

    CREATE TABLE IF NOT EXISTS trades (
        trade_id        TEXT PRIMARY KEY,
        decision_id     TEXT,
        symbol          TEXT NOT NULL,
        side            TEXT NOT NULL,
        volume          REAL NOT NULL,
        entry_price     REAL,
        exit_price      REAL,
        sl              REAL,
        tp              REAL,
        opened_at       TEXT,
        closed_at       TEXT,
        pnl             REAL,
        fees            REAL DEFAULT 0,
        spread          REAL,
        slippage        REAL,
        mae             REAL,
        mfe             REAL,
        holding_time_sec REAL,
        status          TEXT NOT NULL DEFAULT 'OPEN',
        broker_ticket   TEXT,
        strategy_id     TEXT,
        strategy_version INTEGER,
        is_virtual      INTEGER NOT NULL DEFAULT 0,
        metadata_json   TEXT NOT NULL DEFAULT '{}',
        created_at      TEXT NOT NULL,
        updated_at      TEXT NOT NULL,
        UNIQUE(broker_ticket) ON CONFLICT IGNORE,
        FOREIGN KEY (decision_id) REFERENCES decisions(decision_id),
        FOREIGN KEY (strategy_id) REFERENCES strategies(strategy_id)
    );
    CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
    CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
    CREATE INDEX IF NOT EXISTS idx_trades_virtual ON trades(is_virtual);

    CREATE TABLE IF NOT EXISTS positions (
        position_id     TEXT PRIMARY KEY,
        symbol          TEXT NOT NULL,
        side            TEXT NOT NULL,
        volume          REAL NOT NULL,
        entry_price     REAL,
        current_price   REAL,
        sl              REAL,
        tp              REAL,
        unrealized_pnl  REAL,
        broker_ticket   TEXT,
        strategy_id     TEXT,
        opened_at       TEXT NOT NULL,
        updated_at      TEXT NOT NULL,
        status          TEXT NOT NULL DEFAULT 'OPEN',
        is_virtual      INTEGER NOT NULL DEFAULT 0,
        metadata_json   TEXT NOT NULL DEFAULT '{}',
        UNIQUE(broker_ticket) ON CONFLICT IGNORE
    );
    CREATE INDEX IF NOT EXISTS idx_pos_status ON positions(status);

    CREATE TABLE IF NOT EXISTS experiences (
        experience_id   TEXT PRIMARY KEY,
        timestamp       TEXT NOT NULL,
        symbol          TEXT,
        timeframe       TEXT,
        market_state_json TEXT NOT NULL DEFAULT '{}',
        features_json   TEXT NOT NULL DEFAULT '{}',
        regime          TEXT,
        strategy_id     TEXT,
        strategy_version INTEGER,
        action          TEXT,
        entry_price     REAL,
        exit_price      REAL,
        sl              REAL,
        tp              REAL,
        position_size   REAL,
        fees            REAL,
        spread          REAL,
        slippage        REAL,
        mae             REAL,
        mfe             REAL,
        holding_time_sec REAL,
        pnl             REAL,
        reward          REAL,
        outcome         TEXT,
        policy_version  TEXT,
        trade_id        TEXT,
        is_virtual      INTEGER NOT NULL DEFAULT 0,
        created_at      TEXT NOT NULL,
        FOREIGN KEY (strategy_id) REFERENCES strategies(strategy_id),
        FOREIGN KEY (trade_id) REFERENCES trades(trade_id)
    );
    CREATE INDEX IF NOT EXISTS idx_exp_ts ON experiences(timestamp);
    CREATE INDEX IF NOT EXISTS idx_exp_strategy ON experiences(strategy_id);

    CREATE TABLE IF NOT EXISTS experiments (
        experiment_id   TEXT PRIMARY KEY,
        name            TEXT NOT NULL,
        hypothesis_id   TEXT,
        status          TEXT NOT NULL DEFAULT 'PENDING',
        priority        REAL DEFAULT 0,
        config_json     TEXT NOT NULL DEFAULT '{}',
        created_at      TEXT NOT NULL,
        updated_at      TEXT NOT NULL,
        started_at      TEXT,
        finished_at     TEXT
    );
    CREATE INDEX IF NOT EXISTS idx_expmt_status ON experiments(status);

    CREATE TABLE IF NOT EXISTS experiment_results (
        result_id       TEXT PRIMARY KEY,
        experiment_id   TEXT NOT NULL,
        metrics_json    TEXT NOT NULL DEFAULT '{}',
        passed          INTEGER,
        notes           TEXT,
        created_at      TEXT NOT NULL,
        FOREIGN KEY (experiment_id) REFERENCES experiments(experiment_id)
    );
    CREATE INDEX IF NOT EXISTS idx_eres_exp ON experiment_results(experiment_id);

    CREATE TABLE IF NOT EXISTS knowledge_claims (
        claim_id        TEXT PRIMARY KEY,
        source          TEXT,
        url             TEXT,
        title           TEXT,
        author          TEXT,
        publication_date TEXT,
        retrieval_date  TEXT NOT NULL,
        content_hash    TEXT,
        claim           TEXT NOT NULL,
        evidence        TEXT,
        methodology     TEXT,
        dataset         TEXT,
        limitations     TEXT,
        confidence      REAL,
        status          TEXT NOT NULL DEFAULT 'DISCOVERED',
        validation_status TEXT,
        metadata_json   TEXT NOT NULL DEFAULT '{}',
        created_at      TEXT NOT NULL,
        updated_at      TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_know_status ON knowledge_claims(status);
    CREATE INDEX IF NOT EXISTS idx_know_hash ON knowledge_claims(content_hash);

    CREATE TABLE IF NOT EXISTS hypotheses (
        hypothesis_id   TEXT PRIMARY KEY,
        claim_id        TEXT,
        statement       TEXT NOT NULL,
        status          TEXT NOT NULL DEFAULT 'PROPOSED',
        confidence      REAL,
        experiment_id   TEXT,
        created_at      TEXT NOT NULL,
        updated_at      TEXT NOT NULL,
        metadata_json   TEXT NOT NULL DEFAULT '{}',
        FOREIGN KEY (claim_id) REFERENCES knowledge_claims(claim_id),
        FOREIGN KEY (experiment_id) REFERENCES experiments(experiment_id)
    );
    CREATE INDEX IF NOT EXISTS idx_hyp_status ON hypotheses(status);

    CREATE TABLE IF NOT EXISTS risk_events (
        event_id        TEXT PRIMARY KEY,
        timestamp       TEXT NOT NULL,
        event_type      TEXT NOT NULL,
        severity        TEXT NOT NULL DEFAULT 'info',
        symbol          TEXT,
        details_json    TEXT NOT NULL DEFAULT '{}',
        created_at      TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_risk_ts ON risk_events(timestamp);

    CREATE TABLE IF NOT EXISTS capability_events (
        event_id        TEXT PRIMARY KEY,
        timestamp       TEXT NOT NULL,
        provider_id     TEXT,
        provider_name   TEXT,
        capability      TEXT,
        event_type      TEXT NOT NULL,
        details_json    TEXT NOT NULL DEFAULT '{}',
        created_at      TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_capev_ts ON capability_events(timestamp);

    -- Audit log is append-only by convention (no UPDATE/DELETE in repository).
    CREATE TABLE IF NOT EXISTS audit_log (
        audit_id        TEXT PRIMARY KEY,
        timestamp       TEXT NOT NULL,
        component       TEXT NOT NULL,
        action          TEXT NOT NULL,
        entity_type     TEXT,
        entity_id       TEXT,
        old_state_json  TEXT,
        new_state_json  TEXT,
        reason          TEXT,
        evidence_json   TEXT,
        actor           TEXT DEFAULT 'agent',
        created_at      TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_audit_ts ON audit_log(timestamp);
    CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log(entity_type, entity_id);

    CREATE TABLE IF NOT EXISTS model_artifacts (
        artifact_id     TEXT PRIMARY KEY,
        name            TEXT NOT NULL,
        version         TEXT NOT NULL,
        artifact_type   TEXT NOT NULL,
        path            TEXT,
        checksum        TEXT,
        metrics_json    TEXT NOT NULL DEFAULT '{}',
        status          TEXT NOT NULL DEFAULT 'CANDIDATE',
        created_at      TEXT NOT NULL,
        updated_at      TEXT NOT NULL,
        UNIQUE(name, version)
    );
    CREATE INDEX IF NOT EXISTS idx_art_status ON model_artifacts(status);
    """
}
